// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA34aVdtAZDliWbwEoKm58IoATHqC9NfyI',
    appId: '1:339688925328:web:009a2206065d012c5e1015',
    messagingSenderId: '339688925328',
    projectId: 'eventease-4ad4c',
    authDomain: 'eventease-4ad4c.firebaseapp.com',
    storageBucket: 'eventease-4ad4c.firebasestorage.app',
    measurementId: 'G-WSJYZF72N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIfO48EuLgfA2Tk0Cqk3DtUPeWKFUz8PA',
    appId: '1:339688925328:android:1bbb93bc00fc21f45e1015',
    messagingSenderId: '339688925328',
    projectId: 'eventease-4ad4c',
    storageBucket: 'eventease-4ad4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgjVH8eXD17sUZx-pQLKuNjvUX9ZMx_n4',
    appId: '1:339688925328:ios:cee58fa74d4a7f7c5e1015',
    messagingSenderId: '339688925328',
    projectId: 'eventease-4ad4c',
    storageBucket: 'eventease-4ad4c.firebasestorage.app',
    iosBundleId: 'com.example.eventease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgjVH8eXD17sUZx-pQLKuNjvUX9ZMx_n4',
    appId: '1:339688925328:ios:cee58fa74d4a7f7c5e1015',
    messagingSenderId: '339688925328',
    projectId: 'eventease-4ad4c',
    storageBucket: 'eventease-4ad4c.firebasestorage.app',
    iosBundleId: 'com.example.eventease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA34aVdtAZDliWbwEoKm58IoATHqC9NfyI',
    appId: '1:339688925328:web:037c878fd073c74c5e1015',
    messagingSenderId: '339688925328',
    projectId: 'eventease-4ad4c',
    authDomain: 'eventease-4ad4c.firebaseapp.com',
    storageBucket: 'eventease-4ad4c.firebasestorage.app',
    measurementId: 'G-99MB6Q0VQK',
  );
}
